org: pahamihali4
app: post-test-app
service: post-test

plugins:
  - serverless-aws-documentation

provider:
  name: aws
  runtime: python3.8
  region: eu-central-1

custom:
  wsgi:
    app: handler.post_test
    packRequirements: false

functions:
  post_test:
    handler: handler.post_test
    events:
      -
        http:
          path: post_test
          method: post
          # authorizer: aws_iam
          # documentation:
          #   summary: "Get URL load duration"
          #   description: "Get URL load duration"
          #   tags:
          #     - "post-test-dev"
          #     - "arn:aws:cloudformation:eu-central-1:102080805428:stack/post-test-dev/e95218a0-db11-11ea-93a0-06a85d409ac4"
          #     - "PostUnderscoretestLambdaFunction"
          #     - "dev"
          #   requestBody:
          #     description: "The list of urls"
          #   requestHeaders:
          #     -
          #       name: "x-header"
          #       description: "Header description"
          #     -
          #       name: "Authorization"
          #       description: "Auth API key"
          #   methodResponses:
          #     -
          #       statusCode: "200"
          #       responseBody:
          #         description: "The json which contains URLs as keys and duration as value"


          
# plugins:
#   - serverless-aws-documentation
package:
  exclude:
    - node_modules/**
    - .idea/**
    - .vscode/**
    - env/**
    - README.md
    - package.json
    - package-lock.json
    - requirements.txt

# custom:
#   documentation:
#     version: "1"
#title: "dev-post-test	"
#     summary: "Get URL load duration"
#     description: "Get URL load duration"
#     tags:
#       - "post-test-dev"
#       - "arn:aws:cloudformation:eu-central-1:102080805428:stack/post-test-dev/e95218a0-db11-11ea-93a0-06a85d409ac4"
#       - "PostUnderscoretestLambdaFunction"
#       - "dev"
#     requestBody:
#       description: "The list of urls"
#     requestHeaders:
#       -
#         name: "x-header"
#         description: "Header description"
#       -
#         name: "Authorization"
#         description: "Auth API key"
#     methodResponses:
#       -
#         statusCode: "200"
#         responseBody:
#           description: "The json which contains URLs as keys and duration as value"
