org: pahamihali4
app: post-test-app
service: post-test


plugins:
  - serverless-aws-documentation


provider:
  name: aws
  runtime: python3.8
  region: eu-central-1
  apiKeys:
    - API-Key-Get-duration


functions:
  post_test:
    handler: handler.post_test
    events:
      -
        http:
          path: post_test
          method: post
          private: true


package:
  exclude:
    - node_modules/**
    - .idea/**
    - .vscode/**
    - env/**
    - README.md
    - package.json
    - package-lock.json
    - requirements.txt


custom:
  documentation:
    api:
      info:
        version: "1"
        title: "dev-post-test"
        summary: "POST request load url duration"
        description: "There is the urls list in the body. The python handler check the duration of url loading"
        contact:
          name: "Pavlo Mykhalichenko"
          email: "pahamihali4@gmail.com"
    models:
      -
        name: "Duration"
        description: "Get url load duration"
        contentType: "application/json"
      -
        name: "ErrorBadRequestResponse"
        description: "The request body has an empty list of urls"
        contentType: "application/json"
      -
        name: "ErrorNotFoundResponse"
        description: "The current url was not found"
        contentType: "application/json"
    tags:
      - "post-test-dev"
      - "arn:aws:cloudformation:eu-central-1:102080805428:stack/post-test-dev/e95218a0-db11-11ea-93a0-06a85d409ac4"
      - "PostUnderscoretestLambdaFunction"
      - "dev"
    authorizers:
      -
        name: "MyCustomAuthorizer"
        description: "Authorization via x-api-key"
    requestBody:
      description: "The list of urls"
    requestHeaders:
      -
        name: "x-header"
        description: "Post request header with x-api-key"
      -
        name: "Authorization"
        description: "Use API key (x-api-key) for user authorization"
    requestModels:
      "application/json": "Duration"
    methodResponses:
      -
        statusCode: "200"
        responseBody:
          description: "The json which contains URLs as keys and duration as value"
        responseModels:
          "application/json": "Duration"
      -
        statusCode: "400"
        responseModels:
          "application/json": "ErrorBadRequestResponse"
      -
        statusCode: "404"
        responseModels:
          "application/json": "ErrorNotFoundResponse"
